### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by SpotlightKid** [sdangelo/asid#1]
Hello, nice project and interesting blog!

I would like to package A-SID (the VST3 plugin) for the [Arch User Repository](https://aur.archlinux.org). For a package for a specific version of the software, having a release tagged in the repo would make things much easier. Marking that tag as a release in Github would be even better :)

**Comment by SpotlightKid** [comment]
Huh, now there is a tag :)

I could have sworn there was none a few moments ago. Anyway, probably my mistake!

**Comment by sdangelo** [comment]
You were right, I put one after your request.
BTW, if you have any issue packaging this thing do not hesitate and tell me. As a long time ex Arch user I'd be glad to help.

**Comment by SpotlightKid** [comment]
Here's the package: https://aur.archlinux.org/packages/a-sid

**Comment by SpotlightKid** [comment]
Please don't forget to tag the new 1.0.4 release. Thank you.

**Comment by sdangelo** [comment]
Done ;-)
